[custom]

;指定美国
ruleset=🇺🇸美国,https://raw.githubusercontent.com/peiminwu/ACL4SSR/refs/heads/main/proxy-us.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/LinkedIn/LinkedIn.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TruthSocial/TruthSocial.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list

;灵活分流
ruleset=🟢Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list
ruleset=🤖AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list
ruleset=🤖AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list
ruleset=🤖AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Anthropic/Anthropic.list

;指定direct
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Direct/Direct.list
ruleset=DIRECT,[]GEOIP,CN

;剩下全部proxy
ruleset=🗽PROXY,[]FINAL

;设置分组标志位
custom_proxy_group=🗽PROXY`select`[]🇭🇰香港`[]🇺🇸美国`[]🌍其他`[]⚙️手动`
custom_proxy_group=🤖AI`select`[]🇺🇸美国`[]🌍其他`
custom_proxy_group=🟢Spotify`select`[]DIRECT`[]🇭🇰香港`
custom_proxy_group=🇭🇰香港`url-test`(香|HK)`https://twitter.com/favicon.ico`300,,150
custom_proxy_group=🇺🇸美国`url-test`(美|US)`https://twitter.com/favicon.ico`300,,150
custom_proxy_group=🌍其他`url-test`^(?!.*(香|HK|美|US|网址|重置)).*$`https://twitter.com/favicon.ico`300,,150
custom_proxy_group=⚙️手动`select`.*

enable_rule_generator=true
overwrite_original_rules=true
