[custom]

;指定美国
ruleset=🇺🇸美国,https://raw.githubusercontent.com/peiminwu/ACL4SSR/refs/heads/main/proxy-us.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Anthropic/Anthropic.list
ruleset=🇺🇸美国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/LinkedIn/LinkedIn.list

;指定direct
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Direct/Direct.list
ruleset=DIRECT,[]GEOIP,CN

;proxy
ruleset=🗽PROXY,[]FINAL

;设置分组标志位
custom_proxy_group=🗽PROXY`select`[]手动选择`[]🇭🇰香港`[]🇺🇸美国`[]其他`
custom_proxy_group=手动选择`select`.*
custom_proxy_group=🇺🇸美国`url-test`(美|US)`https://twitter.com/favicon.ico`300,,150
custom_proxy_group=🇭🇰香港`url-test`(香|HK)`https://twitter.com/favicon.ico`300,,150
custom_proxy_group=其他`url-test`(JP|TW|SG|日本|台湾|新加坡)`https://twitter.com/favicon.ico`300,,150

enable_rule_generator=true
overwrite_original_rules=true
